### ISSUE TITLE
no longer works with rust 1.0.0

### ISSUE THREAD

**Issue by shadowleaves** [xasmx/rust-la#1]
---

make
mkdir -p out
rustc  --out-dir out --crate-type lib src/lib.rs
src/macros.rs:35:1: 35:2 error: macros that expand to items must either be surrounded with braces or followed by a semicolon
src/macros.rs:35 )
                 ^
src/matrix.rs:60:28: 60:29 error: expected type, found `|`
src/matrix.rs:60   pub fn map<S>(&self, f : |&T| -> S) -> Matrix<S> {
                                            ^
make: **\* [build] Error 101

**Comment by astraw** [comment]
I think this issue can be closed: as of ae39d0493f20b1c5d2afe50a9521130add388128, rust-la compiles and all 92 tests pass. I checked using `cargo test` on rust 1.0.0 rather than the Makefile which I therefore think can be removed. (Note that the commit message says "No guarantees that anything actually works; and will need to do fixes to the api.")

**Comment by xasmx** [comment]
Working in 1.0 now.
